# Generated by Django 3.2.4 on 2021-06-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingvisit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation_beautician',
            name='start_time',
            field=models.TimeField(default='09:00'),
        ),
    ]
