# Generated by Django 3.2.4 on 2021-06-30 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingvisit', '0002_alter_reservation_beautician_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation_beautician',
            name='services',
        ),
        migrations.AddField(
            model_name='reservation_beautician',
            name='services',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookingvisit.bservices'),
            preserve_default=False,
        ),
    ]
