# Generated by Django 3.2.4 on 2021-07-01 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookingvisit', '0003_auto_20210630_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation_beautician',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
