# Generated by Django 3.2.4 on 2021-07-01 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingvisit', '0004_alter_reservation_beautician_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opinions',
            old_name='name',
            new_name='client',
        ),
    ]
