# Generated by Django 3.2.4 on 2021-07-01 17:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookingvisit', '0005_rename_name_opinions_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinions',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation_hairdresser',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation_hairdresser',
            name='day',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
