# Generated by Django 3.2.4 on 2021-07-02 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingvisit', '0006_auto_20210701_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation_hairdresser',
            name='employees',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pracownik', to='bookingvisit.hairdresser'),
        ),
    ]
