# Generated by Django 3.2.4 on 2021-07-02 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingvisit', '0007_alter_reservation_hairdresser_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation_hairdresser',
            name='employees',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingvisit.hairdresser', verbose_name='Pracownik'),
        ),
    ]
