# Generated by Django 3.2.4 on 2021-07-02 07:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingvisit', '0008_alter_reservation_hairdresser_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation_beautician',
            name='day',
            field=models.DateField(default=datetime.date.today, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='reservation_beautician',
            name='employees',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingvisit.beautician', verbose_name='Pracownik'),
        ),
        migrations.AlterField(
            model_name='reservation_beautician',
            name='services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingvisit.bservices', verbose_name='Usługa'),
        ),
        migrations.AlterField(
            model_name='reservation_beautician',
            name='start_time',
            field=models.TimeField(default='09:00', verbose_name='Godzina'),
        ),
        migrations.AlterField(
            model_name='reservation_hairdresser',
            name='day',
            field=models.DateField(default=datetime.date.today, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='reservation_hairdresser',
            name='services',
            field=models.ManyToManyField(to='bookingvisit.HServices', verbose_name='Usługa'),
        ),
        migrations.AlterField(
            model_name='reservation_hairdresser',
            name='start_time',
            field=models.TimeField(default='08:00', verbose_name='Godzina'),
        ),
    ]
